<script src="{{ asset('assets/app/js/waypoints.min.js') }}"></script>
<script src="{{ asset('assets/app/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/app/js/nice-select.min.js') }}"></script>
<script src="{{ asset('assets/app/js/meanmenu.min.js') }}"></script>
<script src="{{ asset('assets/app/js/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('assets/app/js/slick.min.js') }}"></script>
<script src="{{ asset('assets/app/js/magnific-popup.min.js') }}"></script>
<script src="{{ asset('assets/app/js/backtotop.js') }}"></script>
<script src="{{ asset('assets/app/js/ajax-form.js') }}"></script>
<script src="{{ asset('assets/app/js/jquery-ui.min.js') }}"></script>
<script src="{{ asset('assets/app/js/gsap.min.js') }}"></script>
<script src="{{ asset('assets/app/js/ScrollToPlugin.min.js') }}"></script>
<script src="{{ asset('assets/app/js/SplitText.min.js') }}"></script>
<script src="{{ asset('assets/app/js/ScrollTrigger.min.js') }}"></script>
<script src="{{ asset('assets/app/js/jquery.jplayer.min.js') }}"></script>
<script src="{{ asset('assets/app/js/jplayer.playlist.js') }}"></script>
<script src="{{ asset('assets/app/js/main.js') }}"></script>
<script src="{{ asset('assets/app/js/banner.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>